{% set name = "powerlaw" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f9d9cb39ad23af8f6cae165d47020ee8b7fa58f380c356de91ae2625577699e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - matplotlib-base
    - mpmath
    - numpy
    - python
    - scipy
test:
  imports:
    - powerlaw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/jeffalstott/powerlaw
  license: MIT
  license_family: MIT
  license_file: powerlaw.py
  description: |
    powerlaw is a toolbox using the statistical methods developed in
    Clauset et al. 2007 and Klaus et al. 2011 to determine if a probability
    distribution fits a power law.
  summary: Toolbox for testing if a probability distribution fits a power law
  doc_url: https://github.com/jeffalstott/powerlaw/blob/master/README.rst
  dev_url: https://github.com/jeffalstott/powerlaw

extra:
  recipe-maintainers:
    - jaidevjoshi83
